### ISSUE TITLE
pushRestore.sh does not seem to work

### ISSUE THREAD

**Issue by cjohnson318** [code42/crashplan_api_examples#16]
I am having trouble with pushRestore.sh. Line 192 makes a POST request to PushRestoreJob, but I do not see a POST PushRestoreJob call in the API documentation. Is the API documentation out of date?

**Comment by marcejohnson** [comment]
Connor what version of server are you using?

**Comment by akader** [comment]
Hi Connor,
I created a python version of the Push Restore bash example.  I had to make some minor additions to AJ's CODE42 library and believe I ran into a similar issue.  I did not check it into GITHUB but I'd be happy to send you both.   I haven't tested in of 4.1.5 or 4.1.6.

amir


C O D E 4 2
-
Amir Kader
enterprise systems engineer
cell: 312-218-7853

**Comment by akader** [comment]
Try:  api/WebRestoreSession ,  I doubled check the updates I made in July to AJ's library.

### Amir adding following for push restores 07-10-14
cp_api_dataKeyToken = "/api/DataKeyToken"
cp_api_webRestoreSession = "/api/WebRestoreSession"
cp_api_pushRestoreJob = "/api/PushRestoreJob"
Then the ultimate call looks something like this:

payload = {
'webRestoreSessionId' : webRestoreSessionId,
'sourceGuid' : srcGUID,
'targetNodeGuid' : serverGUID,
'acceptingGuid' : targetGUID,
'restorePath' : restorePath,
'pathSet' : file1,
'numBytes' : 1,
'numFiles' : 1,
'showDeleted' : True,
'restoreFullPath': True
}



C O D E 4 2
-
Amir Kader
enterprise systems engineer
cell: 312-218-7853

**Comment by marcejohnson** [comment]
Great discussion.
@Connor I see the POST method for PushRestoreJob documented here:
http://crashplan.com/apidocviewer/#PushRestoreJob
Do you see this on your server as well?

@Amir, you should totally commit your code when its ready and documented!

**Comment by cjohnson318** [comment]
@marcejohnson I am using the 3.6 server.

Thank you @marcejohnson and @akader for the prompt feedback!

**Comment by toddojala** [comment]
Closing.
