### ISSUE TITLE
PushRestore puts all files in a subfolder crashplan-restore-<timestamp>

### ISSUE THREAD

**Issue by jtwaddle** [code42/crashplan_api_examples#23]
There appears to be a big in PushRestore.  It puts all the files in an subfolder crashplan-restore-<timestamp> instead of where I tell it to.  In order for this automated migration tool to be useful for us, we need to put the files in the exact location we specify.  How do we disable the creation of the crashplan-restore-<timestamp> subfolder so it puts the files exactly where we tell it to?

I started a feature request for this:

https://helpdesk.code42.com/entries/98660088-Disable-API-PushRestoreJob-crashplan-restore-subfolder-creation

Go vote for it

**Comment by ajlaventure** [comment]
All restore requests from the API will create a folder called crashplan-restore-<timestamp> and place it in the folder where you requested the restore to be placed.

A restore to current location is not available via the api at this time.  There is an internal feature request for this, however.

Thanks,
